Mouse input
ssnover/my-blaster-runs-hot pull request #16
Opened 2022-07-05 02:45 UTC by dariandzirko

Now we can use a mouse although I am sure a track pad will not be a good time.

2022-07-08 00:19 UTC, ssnover commented on src/constants.rs
> +pub const MAX_BLASTER_HEAT: f32 = 1000.;
Wanna take this out or try to make it configurable somehow?

2022-07-08 01:31 UTC, ssnover commented on src/player.rs
> +        //weapon_data.firing = keys.pressed(KeyCode::RShift);
Should delete.

2022-07-08 01:32 UTC, ssnover commented on src/player.rs
> +    // for ev in cursor_evr.iter() {
Should delete

2022-07-09 04:22 UTC, ssnover requested changes
Constant is still wrong

2022-07-09 04:28 UTC, dariandzirko commented
> Constant is still wrong

This is dumb overheating while prototyping is annoying

2022-07-31 17:15 UTC, ssnover approved these changes

2022-08-04 20:42 UTC, merged